server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    org.springframework.security.oauth2: trace

spring:
  datasource:
    url: jdbc:mariadb://database-1.cntm6woxdkif.us-east-1.rds.amazonaws.com:3306/oauth2
    username: root
    password: D4n1el545836$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:your_client_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your_client_secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: oauth2-client
        provider:
          google:
            user-name-attribute: email

springdoc:
  api-docs:
    version: openapi_3_0
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-oauth2-endpoints: true
  #http://127.0.0.1:9000/login/oauth2/code/messaging-client-oidc
  #
  #http://127.0.0.1:9000/authorized
  #
  #http://127.0.0.1:9000/index
  #
  #http://localhost:9000/login/oauth2/code/google-idp
  #
  #https://oauthdebugger.com/debug
